### ISSUE TITLE
Error when using CLI on Windows (file path problem)

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-validation#101]
I know Linux is our target platform, but for convenience I often use our SDK tools on my Windows machine :D

When trying to validate a project on Windows, I get the following error:

```
$ tng-validate --project descriptors/
CLI input arguments: ['--project', 'descriptors/']
Printing all the arguments: Namespace(api=False, cfile=None, custom=False, dext=None, dpath=None, integrity=False, mode='stateless', nsd=None, package_file=None, project_path='descriptors/', service_address='127.0.0.1', service_port=5001, syntax=False, topology=False, verbose=False, vnfd=None, workspace_path=None)
Project validation
2019-01-23 15:45:52 [INFO] [tngsdk.project.project] Loading project 'descriptors/project.yml'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating project 'descriptors/'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] ... syntax: True, integrity: True, topology: True
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating service 'descriptors/tango_demo-service.yml'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] ... syntax: True, integrity: True, topology: True
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating syntax of service 'eu.5gtango.demo-service.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating integrity of service 'eu.5gtango.demo-service.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating function 'descriptors/tango_default-vnf0.yml'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] ... syntax: True, integrity: True, topology: True, custom: False
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating syntax of function 'eu.5gtango.default-vnf0.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating integrity of function descriptor 'eu.5gtango.default-vnf0.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating topology of function 'eu.5gtango.default-vnf0.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Built topology graph of function 'eu.5gtango.default-vnf0.0.9': [('input', 'vdu01'), ('output', 'vdu01'), ('mgmt', 'br-mgmt'), ('vdu01', 'br-mgmt')]
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating function 'descriptors/tango_default-vnf1.yml'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] ... syntax: True, integrity: True, topology: True, custom: False
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating syntax of function 'eu.5gtango.default-vnf1.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating integrity of function descriptor 'eu.5gtango.default-vnf1.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating topology of function 'eu.5gtango.default-vnf1.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Built topology graph of function 'eu.5gtango.default-vnf1.0.9': [('input', 'vdu01'), ('output', 'vdu01'), ('mgmt', 'br-mgmt'), ('vdu01', 'br-mgmt')]
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating function 'descriptors/tango_default-vnf2.yml'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] ... syntax: True, integrity: True, topology: True, custom: False
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating syntax of function 'eu.5gtango.default-vnf2.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating integrity of function descriptor 'eu.5gtango.default-vnf2.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating topology of function 'eu.5gtango.default-vnf2.0.9'
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Built topology graph of function 'eu.5gtango.default-vnf2.0.9': [('input', 'vdu01'), ('output', 'vdu01'), ('mgmt', 'br-mgmt'), ('vdu01', 'br-mgmt')]
2019-01-23 15:45:52 [INFO] [tngsdk.validation.validator] Validating topology of service 'eu.5gtango.demo-service.0.9'
Traceback (most recent call last):
  File "C:\Users\Stefan\git-repos\work\tango\venv\Scripts\tng-validate-script.py", line 11, in <module>
    load_entry_point('tngsdk.validate==0.1', 'console_scripts', 'tng-validate')()
  File "c:\users\stefan\git-repos\work\tango\venv\lib\site-packages\tngsdk.validate-0.1-py3.7.egg\tngsdk\validation\__init__.py", line 69, in main
    result_validator = cli.dispatch(args, validator)
  File "c:\users\stefan\git-repos\work\tango\venv\lib\site-packages\tngsdk.validate-0.1-py3.7.egg\tngsdk\validation\cli.py", line 119, in dispatch
    if not validator.validate_project(args.project_path):
  File "c:\users\stefan\git-repos\work\tango\venv\lib\site-packages\tngsdk.validate-0.1-py3.7.egg\tngsdk\validation\validator.py", line 317, in validate_project
    return self.validate_service(nsd_file)
  File "c:\users\stefan\git-repos\work\tango\venv\lib\site-packages\tngsdk.validate-0.1-py3.7.egg\tngsdk\validation\validator.py", line 378, in validate_service
    if self._topology and not self._validate_service_topology(service):
  File "c:\users\stefan\git-repos\work\tango\venv\lib\site-packages\tngsdk.validate-0.1-py3.7.egg\tngsdk\validation\validator.py", line 404, in _validate_service_topology
    self.write_service_graphs(service)
  File "c:\users\stefan\git-repos\work\tango\venv\lib\site-packages\tngsdk.validate-0.1-py3.7.egg\tngsdk\validation\validator.py", line 628, in write_service_graphs
    .format(service.id, lvl)))
  File "<decorator-gen-202>", line 2, in write_graphml
  File "C:\Users\Stefan\git-repos\work\tango\venv\lib\site-packages\networkx-1.11-py3.7.egg\networkx\utils\decorators.py", line 198, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/graphs\\eu.5gtango.demo-service.0.9-lvl0.graphml'
```

This works fine under Ubuntu, so I assume it's a problem with some file paths. If this isn't easy to fix, feel free to just close the issue again :)

**Comment by mpeuster** [comment]
Solution idea: https://docs.python.org/2/library/tempfile.html
